"""add users auth

Revision ID: d66479b1d714
Revises: 3f0bcc6a56d3
Create Date: 2026-04-07 01:14:32.210680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd66479b1d714'
down_revision: Union[str, Sequence[str], None] = '3f0bcc6a56d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "user" not in inspector.get_table_names():
        op.create_table(
            "user",
            sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
        op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)

    op.add_column('dailyplan', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dailyplan', 'user', ['owner_id'], ['id'])
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'owner_id')
    op.drop_constraint(None, 'dailyplan', type_='foreignkey')
    op.drop_column('dailyplan', 'owner_id')
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
