site_name: Отчеты по лабораторным работам
site_description: GitHub Pages отчет по практическим и лабораторным работам по web-программированию
site_author: Maksim Ermakov
dev_addr: 127.0.0.1:8001

theme:
  name: mkdocs

nav:
  - Главная: index.md
  - Лабораторная работа 1:
      - Обзор: lr1/index.md
      - Практика 1.1: lr1/practice-1-1.md
      - Практика 1.2: lr1/practice-1-2.md
      - Практика 1.3: lr1/practice-1-3.md
      - Лабораторная работа 1: lr1/lab-1.md
  - Лабораторная работа 2:
      - Обзор: lr2/index.md
      - Задача 1: lr2/task-1.md
      - Задача 2: lr2/task-2.md
